platform :ios, '9.0'
use_frameworks!
target ‘DrinkPoint' do
pod 'LaunchKit'
pod 'Fabric'
pod 'Crashlytics'
pod 'Mapbox-iOS-SDK'
pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :tag => 'v0.6.0'
pod 'GA-SDK-IOS'
end