platform :ios, '9.0'
use_frameworks!
target 'DrinkPoint' do
pod 'Fabric'
pod 'Crashlytics'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Digits'
pod 'mopub-ios-sdk'
pod 'GA-SDK-IOS'
pod 'SpeechKit'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'FBAudienceNetwork'
pod 'LaunchKit'
end